### ISSUE TITLE
应用列表为空，提示添加，但是找不到按钮。

### ISSUE THREAD

**Issue by LinuxSuRen** [ctripcorp/tars#17]
![image](https://user-images.githubusercontent.com/1450685/56712444-2151ac00-6761-11e9-940f-bf90b502a7c2.png)

**Comment by applepeel** [comment]
从django admin或者db中直接添加

**Comment by LinuxSuRen** [comment]
我已经登陆进去 admin 了，但是早不到添加按钮。另外，数据库添加的话，很多信息都不知道怎么加的。

**Comment by applepeel** [comment]
project 表，项目信息本身影响不大
